import { AlertTriangle } from 'lucide-react'

interface DisclaimerBannerProps {
  compact?: boolean
}

export function DisclaimerBanner({ compact = false }: DisclaimerBannerProps) {
  if (compact) {
    return (
      <div className="flex items-center gap-2 bg-amber-50 border border-amber-300 rounded-lg px-3 py-2 text-xs text-amber-800">
        <AlertTriangle className="w-4 h-4 flex-shrink-0 text-amber-600" />
        <span>
          <strong>ESOP outputs are for professional review only.</strong> Not legal, tax, or
          fiduciary advice. Requires independent trustee, ERISA counsel, CPA, and valuation firm
          review.
        </span>
      </div>
    )
  }

  return (
    <div className="bg-amber-50 border-l-4 border-amber-400 rounded-lg p-4">
      <div className="flex items-start gap-3">
        <AlertTriangle className="w-5 h-5 flex-shrink-0 text-amber-600 mt-0.5" />
        <div>
          <p className="text-sm font-semibold text-amber-900 mb-1">
            ESOP Outputs — For Professional Review Only
          </p>
          <p className="text-sm text-amber-800">
            All outputs generated by this system are <strong>preliminary and informational
            only</strong>. Nothing on this page constitutes legal, tax, fiduciary, investment, or
            valuation advice. All ESOP-related outputs <strong>must be independently reviewed
            and validated</strong> by a qualified independent ESOP trustee, ERISA counsel,
            licensed CPA, and accredited business valuation firm before any reliance or action.
          </p>
        </div>
      </div>
    </div>
  )
}
